#!/usr/bin/env python

order_box_dims_inch = {
    'A1': [10, 7, 3.25],
    '1AD': [13.5, 9.5, 3.5],
    '1A5': [13.5, 11, 4.75],
    '1B2': [15.5, 13, 3.5],
    'K3': [19.5, 13, 6.25],
}

def write_plane_obj(f, vertices):
    f.write('f {0} {1} {2} \n'.format(*vertices))
    f.write('f {1} {3} {2}\n'.format(*vertices))

def write_box_obj(f, box):
    f.write('# {} order box\n'.format(box))
    f.write('# units of meters\n')

    f.write('o box{}\n'.format(box))

    (width, length, height) = [d*0.0254 for d in order_box_dims_inch[box]]

    corners = []

    # vertex list
    for z in [0, height]:
        for y in [-length/2, length/2]:
            for x in [-width/2, width/2]:
                # swap y and z for y-up convention
                f.write('v {} {} {}\n'.format(x, z, y))
                corners.append([x, y, z])

    # face list
    write_plane_obj(f, [1, 2, 3, 4])
    for pair in [[1,2], [2,4], [4,3], [3,1]]:
        write_plane_obj(f, [pair[0]+4, pair[1]+4, pair[0], pair[1]])

def write_box_off(f, box):
    (width, length, height) = [d*0.0254 for d in order_box_dims_inch[box]]

    vertices = []
    for z in [0, height]:
        for y in [-length/2, length/2]:
            for x in [-width/2, width/2]:
                vertices.append([x, y, z])

    faces = [[0, 2, 3, 1]]
    for pair in [[0,1],[1,3],[3,2],[2,0]]:
        faces.append([pair[0]+4, pair[0], pair[1], pair[1]+4])

    f.write('OFF\n')
    f.write('# {} order box\n'.format(box))
    f.write('# units of meters\n')
    f.write('{} {}\n'.format(len(vertices), len(faces)))
    for vertex in vertices:
        f.write(' '.join(map(str, vertex)) + '\n')
    for face in faces:
        f.write(' '.join(map(str, [len(face)] + face)) + '\n')

if __name__ == '__main__':
    for box in order_box_dims_inch:
        write_box_obj(open('box-{}.obj'.format(box), 'w'), box)
        write_box_off(open('box-{}.off'.format(box), 'w'), box)
