image: python:2.7

stages:
- Build
- Test

cmake:
    stage: Build
    script:
    - mkdir build
    - cd build
    - cmake -f ..
    - make all
    artifacts:
        paths:
        - bin/
        - lib/

cpp-unittest:
    stage: Test
    script:
    - cd build
    - make test

python-unittest:
    stage: Test
    script:
    - pip install -r requirements.txt
    - python reactor test -c
