image: reactor

stages:
- Build
- Test
- Document

cmake:
    stage: Build
    script:
    - mkdir build && cd build
    - cmake -f ..
    - make all
    artifacts:
        paths:
        - bin/
        - lib/

cpp-unittest:
    stage: Test
    script:
    - mkdir build && cd build
    - cmake -f ..
    - make test

python-unittest:
    stage: Test
    script:
    - pip install -q -r requirements.txt
    - wget http://people.duke.edu/~mtd13/arc-2017/data-030717.tbz2 && tar xvf data-030717.tbz2
    - python reactor test -c

doxygen:
    stage: Document
    script:
    - apt-get update -qq && apt-get install -y -qq doxygen
    - doxygen Doxyfile
    artifacts:
        paths:
        - doc