# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_panel.ui'
#
# Created: Mon Jul  3 13:21:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FrontPanel(object):
    def setupUi(self, FrontPanel):
        FrontPanel.setObjectName("FrontPanel")
        FrontPanel.resize(715, 443)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrontPanel.sizePolicy().hasHeightForWidth())
        FrontPanel.setSizePolicy(sizePolicy)
        FrontPanel.setMaximumSize(QtCore.QSize(16777215, 443))
        FrontPanel.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(FrontPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_8 = QtGui.QWidget(self.centralwidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_12 = QtGui.QFrame(self.widget_8)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkpoints_label = QtGui.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.checkpoints_label.setFont(font)
        self.checkpoints_label.setAlignment(QtCore.Qt.AlignCenter)
        self.checkpoints_label.setWordWrap(True)
        self.checkpoints_label.setObjectName("checkpoints_label")
        self.verticalLayout_3.addWidget(self.checkpoints_label)
        self.checkpoints = QtGui.QScrollArea(self.frame_12)
        self.checkpoints.setFrameShape(QtGui.QFrame.NoFrame)
        self.checkpoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.checkpoints.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.checkpoints.setWidgetResizable(True)
        self.checkpoints.setObjectName("checkpoints")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 195, 93))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.checkpointsLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.checkpointsLayout.setContentsMargins(0, 0, 0, 0)
        self.checkpointsLayout.setObjectName("checkpointsLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.checkpointsLayout.addItem(spacerItem)
        self.checkpoints.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.checkpoints)
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.frame_9 = QtGui.QFrame(self.widget_8)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.faults_label = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.faults_label.setFont(font)
        self.faults_label.setAlignment(QtCore.Qt.AlignCenter)
        self.faults_label.setWordWrap(True)
        self.faults_label.setObjectName("faults_label")
        self.verticalLayout_2.addWidget(self.faults_label)
        self.scrollArea = QtGui.QScrollArea(self.frame_9)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 196, 93))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.faultsLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.faultsLayout.setContentsMargins(0, 0, 0, 0)
        self.faultsLayout.setObjectName("faultsLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.faultsLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.frame_13 = QtGui.QFrame(self.widget_8)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_13)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.simulation_label = QtGui.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.simulation_label.setFont(font)
        self.simulation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.simulation_label.setWordWrap(True)
        self.simulation_label.setObjectName("simulation_label")
        self.verticalLayout_5.addWidget(self.simulation_label)
        self.scrollArea_2 = QtGui.QScrollArea(self.frame_13)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 195, 93))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.simulationLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.simulationLayout.setContentsMargins(0, 0, 0, 0)
        self.simulationLayout.setObjectName("simulationLayout")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.simulationLayout.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.gridLayout.addWidget(self.widget_8, 2, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.run_step_once = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_step_once.sizePolicy().hasHeightForWidth())
        self.run_step_once.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/step_once.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_step_once.setIcon(icon)
        self.run_step_once.setIconSize(QtCore.QSize(32, 32))
        self.run_step_once.setCheckable(True)
        self.run_step_once.setObjectName("run_step_once")
        self.gridLayout_5.addWidget(self.run_step_once, 1, 0, 1, 1)
        self.run_run_once = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_run_once.sizePolicy().hasHeightForWidth())
        self.run_run_once.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/run_once.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_run_once.setIcon(icon1)
        self.run_run_once.setIconSize(QtCore.QSize(32, 32))
        self.run_run_once.setCheckable(True)
        self.run_run_once.setObjectName("run_run_once")
        self.gridLayout_5.addWidget(self.run_run_once, 1, 1, 1, 1)
        self.run_run_all = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_run_all.sizePolicy().hasHeightForWidth())
        self.run_run_all.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/run_all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_run_all.setIcon(icon2)
        self.run_run_all.setIconSize(QtCore.QSize(32, 32))
        self.run_run_all.setCheckable(True)
        self.run_run_all.setObjectName("run_run_all")
        self.gridLayout_5.addWidget(self.run_run_all, 1, 2, 1, 1)
        self.run_full_auto = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_full_auto.sizePolicy().hasHeightForWidth())
        self.run_full_auto.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/warning.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_full_auto.setIcon(icon3)
        self.run_full_auto.setIconSize(QtCore.QSize(32, 32))
        self.run_full_auto.setCheckable(True)
        self.run_full_auto.setObjectName("run_full_auto")
        self.gridLayout_5.addWidget(self.run_full_auto, 1, 3, 1, 1)
        self.run_label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.run_label.setFont(font)
        self.run_label.setAlignment(QtCore.Qt.AlignCenter)
        self.run_label.setObjectName("run_label")
        self.gridLayout_5.addWidget(self.run_label, 0, 0, 1, 4)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_11 = QtGui.QFrame(self.widget)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.job_pick = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_pick.sizePolicy().hasHeightForWidth())
        self.job_pick.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/pick.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.job_pick.setIcon(icon4)
        self.job_pick.setIconSize(QtCore.QSize(32, 32))
        self.job_pick.setCheckable(True)
        self.job_pick.setObjectName("job_pick")
        self.gridLayout_6.addWidget(self.job_pick, 2, 0, 1, 1)
        self.job_stow = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_stow.sizePolicy().hasHeightForWidth())
        self.job_stow.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/stow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.job_stow.setIcon(icon5)
        self.job_stow.setIconSize(QtCore.QSize(32, 32))
        self.job_stow.setCheckable(True)
        self.job_stow.setObjectName("job_stow")
        self.gridLayout_6.addWidget(self.job_stow, 2, 1, 1, 1)
        self.job_final = QtGui.QPushButton(self.frame_11)
        self.job_final.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_final.sizePolicy().hasHeightForWidth())
        self.job_final.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/stow_pick.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.job_final.setIcon(icon6)
        self.job_final.setIconSize(QtCore.QSize(32, 32))
        self.job_final.setCheckable(True)
        self.job_final.setObjectName("job_final")
        self.gridLayout_6.addWidget(self.job_final, 2, 2, 1, 1)
        self.job_label = QtGui.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.job_label.setFont(font)
        self.job_label.setAlignment(QtCore.Qt.AlignCenter)
        self.job_label.setObjectName("job_label")
        self.gridLayout_6.addWidget(self.job_label, 1, 0, 1, 3)
        self.horizontalLayout.addWidget(self.frame_11)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.strategy_panel = QtGui.QWidget(self.centralwidget)
        self.strategy_panel.setMaximumSize(QtCore.QSize(16777215, 0))
        self.strategy_panel.setObjectName("strategy_panel")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.strategy_panel)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtGui.QFrame(self.strategy_panel)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtGui.QFormLayout(self.frame_6)
        self.formLayout.setObjectName("formLayout")
        self.label_18 = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_18)
        self.label_17 = QtGui.QLabel(self.frame_6)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.frame_6)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtGui.QFrame(self.strategy_panel)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_2 = QtGui.QFormLayout(self.frame_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_2 = QtGui.QFrame(self.strategy_panel)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hw_cam_tl = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_tl.sizePolicy().hasHeightForWidth())
        self.hw_cam_tl.setSizePolicy(sizePolicy)
        self.hw_cam_tl.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_tl.setFlat(True)
        self.hw_cam_tl.setObjectName("hw_cam_tl")
        self.gridLayout_4.addWidget(self.hw_cam_tl, 2, 1, 1, 1)
        self.hw_cam_tr = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_tr.sizePolicy().hasHeightForWidth())
        self.hw_cam_tr.setSizePolicy(sizePolicy)
        self.hw_cam_tr.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_tr.setFlat(True)
        self.hw_cam_tr.setObjectName("hw_cam_tr")
        self.gridLayout_4.addWidget(self.hw_cam_tr, 1, 1, 1, 1)
        self.hw_cam_bl = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_bl.sizePolicy().hasHeightForWidth())
        self.hw_cam_bl.setSizePolicy(sizePolicy)
        self.hw_cam_bl.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_bl.setFlat(True)
        self.hw_cam_bl.setObjectName("hw_cam_bl")
        self.gridLayout_4.addWidget(self.hw_cam_bl, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 2)
        self.hw_scale_shelf = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_scale_shelf.sizePolicy().hasHeightForWidth())
        self.hw_scale_shelf.setSizePolicy(sizePolicy)
        self.hw_scale_shelf.setIconSize(QtCore.QSize(16, 16))
        self.hw_scale_shelf.setFlat(True)
        self.hw_scale_shelf.setObjectName("hw_scale_shelf")
        self.gridLayout_4.addWidget(self.hw_scale_shelf, 9, 0, 1, 1)
        self.hw_robot = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_robot.sizePolicy().hasHeightForWidth())
        self.hw_robot.setSizePolicy(sizePolicy)
        self.hw_robot.setIconSize(QtCore.QSize(16, 16))
        self.hw_robot.setFlat(True)
        self.hw_robot.setObjectName("hw_robot")
        self.gridLayout_4.addWidget(self.hw_robot, 1, 0, 1, 1)
        self.hw_cam_br = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_br.sizePolicy().hasHeightForWidth())
        self.hw_cam_br.setSizePolicy(sizePolicy)
        self.hw_cam_br.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_br.setFlat(True)
        self.hw_cam_br.setObjectName("hw_cam_br")
        self.gridLayout_4.addWidget(self.hw_cam_br, 3, 1, 1, 1)
        self.hw_cam_box = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_box.sizePolicy().hasHeightForWidth())
        self.hw_cam_box.setSizePolicy(sizePolicy)
        self.hw_cam_box.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_box.setFlat(True)
        self.hw_cam_box.setObjectName("hw_cam_box")
        self.gridLayout_4.addWidget(self.hw_cam_box, 9, 1, 1, 1)
        self.hw_shelf = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_shelf.sizePolicy().hasHeightForWidth())
        self.hw_shelf.setSizePolicy(sizePolicy)
        self.hw_shelf.setIconSize(QtCore.QSize(16, 16))
        self.hw_shelf.setFlat(True)
        self.hw_shelf.setObjectName("hw_shelf")
        self.gridLayout_4.addWidget(self.hw_shelf, 2, 0, 1, 1)
        self.hw_gripper = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_gripper.sizePolicy().hasHeightForWidth())
        self.hw_gripper.setSizePolicy(sizePolicy)
        self.hw_gripper.setIconSize(QtCore.QSize(16, 16))
        self.hw_gripper.setFlat(True)
        self.hw_gripper.setObjectName("hw_gripper")
        self.gridLayout_4.addWidget(self.hw_gripper, 3, 0, 1, 1)
        self.hw_cam_tote = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_cam_tote.sizePolicy().hasHeightForWidth())
        self.hw_cam_tote.setSizePolicy(sizePolicy)
        self.hw_cam_tote.setIconSize(QtCore.QSize(16, 16))
        self.hw_cam_tote.setFlat(True)
        self.hw_cam_tote.setObjectName("hw_cam_tote")
        self.gridLayout_4.addWidget(self.hw_cam_tote, 10, 1, 1, 1)
        self.hw_scale_tote = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_scale_tote.sizePolicy().hasHeightForWidth())
        self.hw_scale_tote.setSizePolicy(sizePolicy)
        self.hw_scale_tote.setIconSize(QtCore.QSize(16, 16))
        self.hw_scale_tote.setFlat(True)
        self.hw_scale_tote.setObjectName("hw_scale_tote")
        self.gridLayout_4.addWidget(self.hw_scale_tote, 10, 0, 1, 1)
        self.hw_vacuum = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_vacuum.sizePolicy().hasHeightForWidth())
        self.hw_vacuum.setSizePolicy(sizePolicy)
        self.hw_vacuum.setIconSize(QtCore.QSize(16, 16))
        self.hw_vacuum.setFlat(True)
        self.hw_vacuum.setObjectName("hw_vacuum")
        self.gridLayout_4.addWidget(self.hw_vacuum, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtGui.QFrame(self.strategy_panel)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_3 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.strategy_panel, 3, 0, 1, 1)
        self.widget_6 = QtGui.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_10 = QtGui.QFrame(self.widget_6)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selected_item = QtGui.QLabel(self.frame_10)
        self.selected_item.setWordWrap(True)
        self.selected_item.setObjectName("selected_item")
        self.gridLayout_2.addWidget(self.selected_item, 1, 0, 1, 1)
        self.selected_location = QtGui.QLabel(self.frame_10)
        self.selected_location.setWordWrap(True)
        self.selected_location.setObjectName("selected_location")
        self.gridLayout_2.addWidget(self.selected_location, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.selected_item_icon = QtGui.QLabel(self.frame_10)
        self.selected_item_icon.setText("")
        self.selected_item_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.selected_item_icon.setObjectName("selected_item_icon")
        self.gridLayout_2.addWidget(self.selected_item_icon, 0, 1, 3, 1)
        self.horizontalLayout_4.addWidget(self.frame_10)
        self.frame_3 = QtGui.QFrame(self.widget_6)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mc_stop = QtGui.QPushButton(self.frame_3)
        self.mc_stop.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_stop.sizePolicy().hasHeightForWidth())
        self.mc_stop.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mc_stop.setIcon(icon7)
        self.mc_stop.setIconSize(QtCore.QSize(32, 32))
        self.mc_stop.setObjectName("mc_stop")
        self.gridLayout_3.addWidget(self.mc_stop, 1, 3, 1, 1)
        self.mc_reset = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_reset.sizePolicy().hasHeightForWidth())
        self.mc_reset.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mc_reset.setIcon(icon8)
        self.mc_reset.setIconSize(QtCore.QSize(32, 32))
        self.mc_reset.setObjectName("mc_reset")
        self.gridLayout_3.addWidget(self.mc_reset, 1, 4, 1, 1)
        self.mc_label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mc_label.setFont(font)
        self.mc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_label.setObjectName("mc_label")
        self.gridLayout_3.addWidget(self.mc_label, 0, 1, 1, 4)
        self.mc_back = QtGui.QPushButton(self.frame_3)
        self.mc_back.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_back.sizePolicy().hasHeightForWidth())
        self.mc_back.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mc_back.setIcon(icon9)
        self.mc_back.setIconSize(QtCore.QSize(32, 32))
        self.mc_back.setObjectName("mc_back")
        self.gridLayout_3.addWidget(self.mc_back, 1, 1, 1, 1)
        self.mc_run = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_run.sizePolicy().hasHeightForWidth())
        self.mc_run.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mc_run.setIcon(icon10)
        self.mc_run.setIconSize(QtCore.QSize(32, 32))
        self.mc_run.setObjectName("mc_run")
        self.gridLayout_3.addWidget(self.mc_run, 1, 2, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 1)
        FrontPanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrontPanel)
        QtCore.QMetaObject.connectSlotsByName(FrontPanel)
        FrontPanel.setTabOrder(self.mc_back, self.mc_run)
        FrontPanel.setTabOrder(self.mc_run, self.mc_stop)
        FrontPanel.setTabOrder(self.mc_stop, self.mc_reset)
        FrontPanel.setTabOrder(self.mc_reset, self.hw_robot)

    def retranslateUi(self, FrontPanel):
        FrontPanel.setWindowTitle(QtGui.QApplication.translate("FrontPanel", "ARC Reactor - http://localhost:8888/", None, QtGui.QApplication.UnicodeUTF8))
        self.checkpoints_label.setText(QtGui.QApplication.translate("FrontPanel", "Checkpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.faults_label.setText(QtGui.QApplication.translate("FrontPanel", "Faults", None, QtGui.QApplication.UnicodeUTF8))
        self.simulation_label.setText(QtGui.QApplication.translate("FrontPanel", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.run_step_once.setText(QtGui.QApplication.translate("FrontPanel", "Step\n"
"Once", None, QtGui.QApplication.UnicodeUTF8))
        self.run_run_once.setText(QtGui.QApplication.translate("FrontPanel", "Run\n"
"Once", None, QtGui.QApplication.UnicodeUTF8))
        self.run_run_all.setText(QtGui.QApplication.translate("FrontPanel", "Run\n"
"All", None, QtGui.QApplication.UnicodeUTF8))
        self.run_full_auto.setText(QtGui.QApplication.translate("FrontPanel", "Full\n"
"Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.run_label.setText(QtGui.QApplication.translate("FrontPanel", "Run Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.job_pick.setToolTip(QtGui.QApplication.translate("FrontPanel", "Step Back", None, QtGui.QApplication.UnicodeUTF8))
        self.job_pick.setText(QtGui.QApplication.translate("FrontPanel", "Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.job_pick.setShortcut(QtGui.QApplication.translate("FrontPanel", "Shift+F8", None, QtGui.QApplication.UnicodeUTF8))
        self.job_stow.setToolTip(QtGui.QApplication.translate("FrontPanel", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.job_stow.setText(QtGui.QApplication.translate("FrontPanel", "Stow", None, QtGui.QApplication.UnicodeUTF8))
        self.job_stow.setShortcut(QtGui.QApplication.translate("FrontPanel", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.job_final.setToolTip(QtGui.QApplication.translate("FrontPanel", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.job_final.setText(QtGui.QApplication.translate("FrontPanel", "Stow\n"
"Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.job_final.setShortcut(QtGui.QApplication.translate("FrontPanel", "Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.job_label.setText(QtGui.QApplication.translate("FrontPanel", "Job Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("FrontPanel", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("FrontPanel", "Done:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("FrontPanel", "Remain:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("FrontPanel", "Feasible:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("FrontPanel", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FrontPanel", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FrontPanel", "Remain:", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_tl.setText(QtGui.QApplication.translate("FrontPanel", "Cam TL", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_tr.setText(QtGui.QApplication.translate("FrontPanel", "Cam TR", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_bl.setText(QtGui.QApplication.translate("FrontPanel", "Cam BL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FrontPanel", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_scale_shelf.setText(QtGui.QApplication.translate("FrontPanel", "Scale Shelf", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_robot.setText(QtGui.QApplication.translate("FrontPanel", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_br.setText(QtGui.QApplication.translate("FrontPanel", "Cam BR", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_box.setText(QtGui.QApplication.translate("FrontPanel", "Cam Box", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_shelf.setText(QtGui.QApplication.translate("FrontPanel", "Shelf", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_gripper.setText(QtGui.QApplication.translate("FrontPanel", "Gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_cam_tote.setText(QtGui.QApplication.translate("FrontPanel", "Cam Tote", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_scale_tote.setText(QtGui.QApplication.translate("FrontPanel", "Scale Tote", None, QtGui.QApplication.UnicodeUTF8))
        self.hw_vacuum.setText(QtGui.QApplication.translate("FrontPanel", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FrontPanel", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FrontPanel", "Current:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FrontPanel", "Expected:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FrontPanel", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_item.setText(QtGui.QApplication.translate("FrontPanel", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_location.setText(QtGui.QApplication.translate("FrontPanel", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FrontPanel", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_stop.setToolTip(QtGui.QApplication.translate("FrontPanel", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_stop.setText(QtGui.QApplication.translate("FrontPanel", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_stop.setShortcut(QtGui.QApplication.translate("FrontPanel", "Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_reset.setToolTip(QtGui.QApplication.translate("FrontPanel", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_reset.setText(QtGui.QApplication.translate("FrontPanel", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_reset.setShortcut(QtGui.QApplication.translate("FrontPanel", "Ctrl+Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_label.setText(QtGui.QApplication.translate("FrontPanel", "Master Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_back.setToolTip(QtGui.QApplication.translate("FrontPanel", "Step Back", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_back.setText(QtGui.QApplication.translate("FrontPanel", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_back.setShortcut(QtGui.QApplication.translate("FrontPanel", "Shift+F8", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_run.setToolTip(QtGui.QApplication.translate("FrontPanel", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_run.setText(QtGui.QApplication.translate("FrontPanel", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.mc_run.setShortcut(QtGui.QApplication.translate("FrontPanel", "F5", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
