#!/usr/bin/env python

import os
import cv2
import numpy

paths = [ path for path in os.listdir('.') if os.path.isdir(path)]

for name in paths:
    img = cv2.imread('{0}/{0}_Top_01.png'.format(name))

    if img is None:
        continue

    mask = img.astype(numpy.int).sum(axis=2) > 10
    black = img.astype(numpy.int).sum(axis=2) == 0

    contours, _ = cv2.findContours(mask.astype(numpy.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    bounding_contour = max(contours, key=lambda c: cv2.contourArea(c))

    alpha = numpy.zeros(img.shape[:2])
    cv2.drawContours(alpha, [bounding_contour], 0, (255), thickness=-1)
    #alpha[black] = 0

    out = numpy.dstack((img, alpha))

    # x = bounding_contour[:, :, 0]
    # y = bounding_contour[:, :, 1]
    # out = out[x.min():x.max()+1, y.min():y.max()+1, :]

    out = cv2.resize(out, (64, 64))
    cv2.imwrite('{0}/thumb.png'.format(name), out)

    print name
